### ISSUE TITLE
Should local mapping_dict be csv

### ISSUE THREAD

**Issue by alexhamiltonRN** [CONDUITlab/ccdef#8]
We are storing mapping info (loinc short name etc) as dataset in h5 - why propose different ingest format here? Also, is it easier for teams to maintain local mappings in tabular format? <- prob!

**Comment by prlaird** [comment]
The goal is that the hdf5 file is completely self describing, thus the loinc codes should be in the file. Ultimately sites that generate data would include loinc codes in the files they create by coding it into the acquisition pipeline. I agree that the mapping dict could be a csv that is used by the conversion code when we are batch converting existing files. What we want to avoid is an end user needing to have the csv file in order to make sense of the hdf5 file that they obtain from a remote site.

**Comment by alexhamiltonRN** [comment]
Updated LoincMapper to ingest csv
